docs: add content for module 3
asyncapi/learning-paths pull request #5
Opened 2023-11-28 10:07 UTC by mhmohona

**Description**
Added content for module 3 -

> AsyncAPI Specification  (SCENE) Eve helps Chan program his spaceship, so they can stay in touch.
Deep dive into various components of AsyncAPI: info, channels, components, tags, etc.
How to define operations (like send and address), messages, and schemas.

**Related issue(s)**
https://github.com/asyncapi/website/issues/1520

2023-12-05 14:49 UTC, TRohit20 commented on 100-level-AsyncAPI-Intro/step2.md
> +
I think you can remove these lines as I begin the module with a similar storyline, touch lightly on structure and lead to `deep dive of various components`, the rest fits in well and needs to modification for now as I see.

2023-12-05 17:07 UTC, alequetzalli commented
Hey folks, so please update your planet names to:
- Eve's planet: **Capuccinova**
- Chan's planet: **Brownieterra**

2024-01-15 12:48 UTC, derberg reviewed
lgtm

only remark is the host of the server: `space.mosquitto.org`

it is not real, and also afaik in killercoda it is not possible to go outside the killercoda network, this is why in my interactive tutorial I started MQTT broker locally in killercoda container, so I think you need to use localhost - cause you will not be able to use sample document for code generation or other things in killercode

on to you @alequetzalli

2024-01-25 01:24 UTC, alequetzalli commented
@mhmohona ping ping, please make sure to address the important feedback that @derberg left last week :)

2024-01-27 02:44 UTC, alequetzalli commented on 100-level-AsyncAPI-Intro/step2.md
> +## Understanding AsyncAPI Components through Chan and Eve's Programming Session
```suggestion
## Understanding AsyncAPI components 
```

2024-01-27 02:47 UTC, alequetzalli commented on 100-level-AsyncAPI-Intro/step2.md
> +```
```suggestion
- **Info (Metadata about the API):**

Just as the name tag on Chan's spaceship provides essential details like the spaceship's name and model, the `info` section in AsyncAPI serves a similar purpose. It provides crucial information about the API, such as the title, version, and description. The `info` metadata helps developers understand the basic API details they're working with.

```yml
asyncapi: '3.0.0'
info:
  title: Space Communication API
  version: '1.0.0'
  description: API for communication between Chan's spaceship and Capuccinova
```
```

2024-01-27 02:53 UTC, alequetzalli commented on 100-level-AsyncAPI-Intro/step2.md
> +```
```suggestion
- **Servers**

Imagine that Chan's spaceship communicates with Eve on Capuccinova through various servers. In AsyncAPI, the `servers` section describes the servers our API will communicate with, including their hosts, protocols, and descriptions.

```yml
servers:
  production:
    host: space.mosquitto.org
    protocol: mqtt
    description: Production server for space communication
```
```

2024-01-27 02:53 UTC, alequetzalli commented on 100-level-AsyncAPI-Intro/step2.md
> +- **Channels (Communication channels in the API):**
```suggestion
- **Channels**
```

2024-01-27 02:59 UTC, alequetzalli commented on 100-level-AsyncAPI-Intro/step2.md
> +```
```suggestion
The spaceship's radio stations, which correspond to specific topics like communicating with Capuccinova, are similar to the `channels` in AsyncAPI. These channels represent paths for sending specific types of messages. Each channel uses an address, which is a template for the URL of the server, and can have variables inside curly braces.

```yml
channels:
  roomidchat:
    address: chat/{roomId}
    messages:
      chatMessage:
        name: ChatMessage
        payload:
          type: object
          properties:
            userId:
              type: string
              description: The ID of the user who sent the message
            message:
              type: string
              description: The chat message
            spacename:
              type: string
              description: The unique spacename identifier for the message
```
```

2024-01-27 03:01 UTC, alequetzalli commented on 100-level-AsyncAPI-Intro/step2.md
> +```
```suggestion
- **Tags**

`Tags` in AsyncAPI are like the labels on the spaceship's control panel. They help categorize different operations, making it easier to understand what each part of the API does. Each tag consists of a name and an optional description.

```yml
tags:
  - name: chat
    description: Operations related to chat
```
```

2024-01-27 03:14 UTC, alequetzalli commented on 100-level-AsyncAPI-Intro/step2.md
> +```
```suggestion
- **Components**

`Component` is like the toolbox in Chan's spaceship. It contains reusable parts like message definitions and schemas that can be used across the API. Each component is linked to a particular schema, which describes the structure of the message content.

```yml
components:
  messages:
    ChatMessage:
      name: ChatMessage
      title: Chat Message
      contentType: application/json
      payload:
        $ref: '#/components/schemas/ChatMessagePayload'
  schemas:
    ChatMessagePayload:
      type: object
      properties:
        userId:
          type: string
          description: The ID of the user who sent the message
        message:
          type: string
          description: The chat message
```
```

2024-01-27 03:14 UTC, alequetzalli commented on 100-level-AsyncAPI-Intro/step2.md
> +## Programming Operations, Messages, and Schemas
```suggestion
## Operations, messages, and schemas
```

2024-01-27 03:19 UTC, alequetzalli commented on 100-level-AsyncAPI-Intro/step2.md
> +```
```suggestion
- **Operations**

`Operations` in AsyncAPI are like the instructions for the spaceship. They define what actions can be performed within each channel, such as sending or receiving messages. Each operation is associated with a message and a schema.

```yml
operations:
  sendChatMessage:
    action: 'send'
    summary: Send a chat message to a specific room
    channel:
      $ref: '#/channels/roomidchat'
```
```

2024-01-27 03:20 UTC, alequetzalli commented on 100-level-AsyncAPI-Intro/step2.md
> +```
```suggestion
- **Messages**

`Messages` in AsyncAPI are the content exchanged during operations, just like the words Eve from Capuccinova and Chan from Brownieterra use to communicate. They describe the structure and content of the messages sent or received.


```yml
components:
  messages:
    ChatMessage:
      name: ChatMessage
      title: Chat Message
      contentType: application/json
      payload:
        $ref: '#/components/schemas/ChatMessagePayload'
```
```

2024-01-27 03:24 UTC, alequetzalli commented on 100-level-AsyncAPI-Intro/step2.md
> +```
```suggestion
- **Schemas**

`Schemas` in AsyncAPI are like the blueprints for the spaceship. They define the structure of the message content, ensuring that everything fits together correctly. Each schema is associated with a component and describes the structure and content of the messages.

```yml
components:
  schemas:
    ChatMessagePayload:
      type: object
      properties:
        userId:
          type: string
          description: The ID of the user who sent the message
        message:
          type: string
          description: The chat message
```
```

2024-01-27 03:26 UTC, alequetzalli commented on 100-level-AsyncAPI-Intro/step2.md
> +
@mhmohona This line shows clear plagiarism from chatgpt.

2024-01-27 03:29 UTC, alequetzalli commented on 100-level-AsyncAPI-Intro/step2.md
> +---
```suggestion
Now it's time to help Chan establish a sophisticated communication system with Eve on Capuccinova. With your new expertise in AsyncAPI, you'll assist him in creating an AsyncAPI document from scratch.

```

2024-01-27 03:30 UTC, alequetzalli commented on 100-level-AsyncAPI-Intro/step2.md
> +#### Chapter 1: Initiating the Capuccinova Communication Link
```suggestion
#### Exercise 1: Initiate Capuccinova communication
```

2024-01-27 03:33 UTC, alequetzalli commented on 100-level-AsyncAPI-Intro/step2.md
> +**Your Mission: Creating the Base AsyncAPI Document**
```suggestion
```

2024-01-27 03:41 UTC, alequetzalli commented on 100-level-AsyncAPI-Intro/step2.md
> +1. **Start the Journey**: In the KillerCoda terminal, create a new file by typing `nano chan-to-capuccinova.yaml`.
```suggestion
1. In the KillerCoda terminal, create a new file by typing `nano chan-to-capuccinova.yaml`.
```

2024-01-27 03:42 UTC, alequetzalli commented on 100-level-AsyncAPI-Intro/step2.md
> +2. **Lay the Cosmic Foundations**: Enter the basic AsyncAPI structure:
```suggestion
2. Enter the following AsyncAPI document structure:
```

2024-01-27 03:44 UTC, alequetzalli commented on 100-level-AsyncAPI-Intro/step2.md
> +4. **Inform Chan**: Let him know that the foundation for his AsyncAPI document is set.
```suggestion
3. Save (`Ctrl + O`, `Enter`) and exit Nano (`Ctrl + X`).
```

I'm unsure if we need this step inside Killercoda. It's hard to review this file outside of Killercoda.

2024-01-27 03:53 UTC, alequetzalli commented on 100-level-AsyncAPI-Intro/step2.md
> +After successfully laying the groundwork for communication with Capuccinova, Chan is now eager to extend his AsyncAPI document to include a channel for Brownieterra.
```suggestion
#### Exercise 2: Add new channel and define operations**

After successfully laying the groundwork for communication with Capuccinova, Chan is eager to extend his AsyncAPI document to include a channel for Brownieterra. 
```

2024-01-27 04:08 UTC, alequetzalli commented on 100-level-AsyncAPI-Intro/step2.md
> +5. **Inform Chan**: Let Chan know that the new channel for Brownieterra has been successfully added and configured in his AsyncAPI document.
```suggestion
1. Run the command `nano chan-to-capuccinova.yaml` to edit Chan's document.

2. Add a channel for Brownieterra, specifying the channel name, its address, and parameters:
   ```yaml
   brownieterra-chat:
     description: Channel for sending messages to Brownieterra
     address: brownieterra-chat/{spacename}
     parameters:
       spacename:
         description: The unique spacename identifier for Brownieterra communication
         schema:
           type: string
   ```

3. Under the `operations` section, specify how messages will be sent over the new Brownieterra channel.
   ```yaml
   operations:
     sendToBrownieterra:
       action: send
       summary: Send a message to Brownieterra
       channel:
         $ref: '#/channels/brownieterra-chat'
   ```

4. Save your changes (`Ctrl + O`, `Enter`) and exit Nano (`Ctrl + X`).
```

I'm unsure if we actually need step 4, saving changes/closing nano. Does not seem needed if this is in Killercoda.

2024-01-27 04:18 UTC, alequetzalli commented on 100-level-AsyncAPI-Intro/step2.md
> +4. **Update Chan**: Let him know that the message formats are now more detailed and well structured for both Capuccinova and Brownieterra.
```suggestion
```

This is not an exercise as no steps were added. Removing.

2024-02-13 12:53 UTC, smoya requested changes
I noticed there are 3 PR's opened pointing to the exact same file `step2.md`. 

- https://github.com/asyncapi/learning-paths/pull/5
- https://github.com/asyncapi/learning-paths/pull/9
- https://github.com/asyncapi/learning-paths/pull/11

Please unify all of those into one single PR so we can review the file as a whole. 

cc @TRohit20 @mhmohona @alequetzalli

2024-02-14 01:27 UTC, quetzalliwrites commented
> I noticed there are 3 PR's opened pointing to the exact same file `step2.md`.
> 
> * [docs: add content for module 3 #5](https://github.com/asyncapi/learning-paths/pull/5)
> * [docs: adding content for module 3 #9](https://github.com/asyncapi/learning-paths/pull/9)
> * [docs: adding request/reply content in module-3 #11](https://github.com/asyncapi/learning-paths/pull/11)
> 
> Please unify all of those into one single PR so we can review the file as a whole.

I hear you, let's follow your suggestion 😸 .  @TRohit20, can you please handle this one?

2024-02-14 05:11 UTC, TRohit20 commented
@alequetzalli Sure, I'd just have to close all the PRs to begin with and then merge the content into a single document which is anyhow the final output and raise a PR reflecting it.

Would you like me to proceed with that? @alequetzalli + I'm unsure if I have the repo right to close @mhmohona's PR

2024-02-14 05:27 UTC, mhmohona commented
I will close my PR then, will it help?

2024-02-14 05:28 UTC, closed without merging